import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const rixRegular = localFont({
    src: [
        {
            path: '../../public/fonts/RixRegular.woff2',
            weight: '400'
        }
    ],
    variable: '--font-rix',
    weight: '400'
});

// const cookieRunBlack = localFont({
//     src: '/fonts/CookieRunBlack.woff',
//     variable: '--font-cookie-black',
//     weight: '900'
// });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`
                ${rixRegular.variable}
                antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
